# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Rv < Formula
  desc "Generate SVG visualizations of directory structures"
  homepage "https://github.com/grahambrooks/rv"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.10.1/rv-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "0c5f5f5fe97205dab726f7610e2067e792dbd1d6fd58b94ebed50e7a800bbe27"
    end
    on_intel do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.10.1/rv-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "ac4460be08626cda12c43dd5ce071f5881dcd4c16c853fc2ba80d1241dfa2447"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.10.1/rv-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9942aca45a1ec56e8e0349896ba28c732143eccdf31fef76d9f1d7b76e75181b"
    end
    on_intel do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.10.1/rv-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e992680bf04971dc0fd3e249d5701e9d49e7397b87a5a95f7836ee55bb7046ad"
    end
  end

  def install
    bin.install "rv"
  end

  test do
    assert_path_exists bin/"rv"
  end
end
