# Generated by scripts/release.py (release-kit) from the v2026.9.0 release — do not edit.
class Rv < Formula
  desc "Generate SVG visualizations of directory structures"
  homepage "https://github.com/grahambrooks/rv"
  version "2026.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.9.0/rv-v2026.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "1b05cea129c28a99878772a70726c7d78cc039441b4f021d318b907e762a3d23"
    end
    on_intel do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.9.0/rv-v2026.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "9245bbfd093c388e9a4952e4f44dab3905c26796c01260d74001f124bc099e3f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.9.0/rv-v2026.9.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1cc43cf792a32e9dc274f7bec4c5012cc26bd5e0f3ea7b35ae02a6aea5a8a372"
    end
    on_intel do
      url "https://github.com/grahambrooks/rv/releases/download/v2026.9.0/rv-v2026.9.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "380c269a88b7b458daf5b9b6f3322ca17fb639a4089b600dcbaa9615be23bf75"
    end
  end

  def install
    bin.install "rv"
  end

  test do
    assert_path_exists bin/"rv"
  end
end
